### ISSUE TITLE
Demo / Presentation

### ISSUE THREAD

**Issue by aetzion1** [penpost/penpost-web#14]
- [x] Create presentation slides (Adam wants to do!)
- [x] Record backup recording (project requirement)
- [x] Include problem you are trying to solve and how your app does that
- [x] Include challenges on the FE and BE and solutions to those challenges

Day-of Agenda (work in progress)
     * 1 min app overview 
     * 10 min demo
     * 10 min Q&A / Detail on certain points

**Comment by gaj23** [comment]
Please add your postcard picture.
